version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8200:8200"
    environment:
      - DB_HOST=db         
      - DB_USER=retro_user  
      - DB_PASSWORD=1234   
    
    depends_on:
      db:
        condition: service_healthy 


  db:

    image: mysql:8.0
     
    restart: unless-stopped
    
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: app             
      MYSQL_USER: retro_user           
      MYSQL_PASSWORD: 1234             
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s 
      timeout: 5s  
      retries: 5   

