# הגדרת גרסת הפורמט של Docker Compose
version: '3.8'

# הגדרת כל השירותים (הקונטיינרים) שמרכיבים את האפליקציה
services:
  # הגדרת שירות אפליקציית הפייתון
  app:
    # הנחיה לבנות את האימג' מה-Dockerfile שנמצא בתיקייה הנוכחית
    build: .
    # הגדרה להפעיל מחדש את הקונטיינר באופן אוטומטי אם הוא נופל
    restart: always
    # מיפוי פורטים מהמחשב המארח (host) אל הקונטיינר
    # פורמט: HOST:CONTAINER
    ports:
      # ממפה את פורט 8080 במחשב שלך לפורט 8080 בקונטיינר (עבור backend.py)
      - "8080:8080"
      # ממפה את פורט 8200 במחשב שלך לפורט 8200 בקונטיינר (עבור stock_api.py)
      - "8200:8200"
    # הגדרת משתני סביבה עבור קונטיינר האפליקציה
    # משתנים אלו משמשים בקוד הפייתון כדי להתחבר למסד הנתונים
    environment:
      - DB_HOST=db          # שם השירות של מסד הנתונים (משמש כ-hostname)
      - DB_USER=retro_user  # שם המשתמש למסד הנתונים
      - DB_PASSWORD=1234    # סיסמת המשתמש (תוקנה טעות הקלדה)
      - DB_NAME=app         # שם מסד הנתונים
    # הגדרת תלות של שירות זה בשירות מסד הנתונים
    # שירות 'app' לא יתחיל לפעול עד ששירות 'db' יהיה מוכן
    depends_on:
      - db

  # הגדרת שירות מסד הנתונים של MySQL
  db:
    # שימוש באימג' הרשמי של MySQL בגרסה 8.0
    image: mysql:8.0
    # הפעלה מחדש אוטומטית במקרה של נפילה
    restart: always
    # הגדרת משתני סביבה הנדרשים לאתחול הראשוני של קונטיינר MySQL
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # סיסמה למשתמש ה-root של MySQL
      MYSQL_DATABASE: app               # יוצר אוטומטית מסד נתונים בשם 'app'
      MYSQL_USER: retro_user            # יוצר אוטומטית משתמש בשם 'retro_user'
      MYSQL_PASSWORD: 1234              # מגדיר את הסיסמה עבור 'retro_user'
    # מיפוי פורט ה-MySQL הסטנדרטי מהמחשב המארח לקונטיינר
    # מאפשר להתחבר למסד הנתונים גם כלים חיצוניים מהמחשב שלך במידת הצורך
    ports:
      - "3306:3306"
    # הגדרת volume לאחסון קבוע של המידע ולאתחול מסד הנתונים
    volumes:
      # השורה הזו היא החלק המרכזי: היא מקשרת את תיקיית 'mysql-init' המקומית
      # לתיקייה מיוחדת בקונטיינר. MySQL יריץ אוטומטית כל קובץ .sql שיימצא
      # בתיקייה זו בעת ההפעלה הראשונה של הקונטיינר.
      - ./mysql-init:/docker-entrypoint-initdb.d
