# הגדרת גרסת הפורמט של Docker Compose. גרסה 3.8 היא מודרנית ויציבה.
version: '3.8'

# הגדרת כל השירותים (הקונטיינרים) שמרכיבים את האפליקציה
services:
  # הגדרת שירות אפליקציית הפייתון
  app:
    # הנחיה לבנות את האימג' מה-Dockerfile שנמצא בתיקייה הנוכחית
    build: .
    # הגדרה להפעיל מחדש את הקונטיינר באופן אוטומטי אם הוא נופל, אלא אם כן הוא נעצר ידנית
    restart: unless-stopped
    # מיפוי פורטים מהמחשב המארח (host) אל הקונטיינר
    ports:
      # ממפה את פורט 8080 במחשב שלך לפורט 8080 בקונטיינר (עבור ה-backend)
      - "8080:8080"
      # ממפה את פורט 8200 במחשב שלך לפורט 8200 בקונטיינר (עבור ה-stock_api)
      - "8200:8200"
    # הגדרת משתני סביבה עבור קונטיינר האפליקציה
    environment:
      - DB_HOST=db          # שם השירות של מסד הנתונים. כך האפליקציה מוצאת אותו ברשת של דוקר.
      - DB_USER=retro_user  # שם המשתמש למסד הנתונים
      - DB_PASSWORD=1234    # סיסמת המשתמש
      - DB_NAME=app         # שם מסד הנתונים
    # הגדרת תלות של שירות זה בשירות מסד הנתונים
    depends_on:
      db:
        condition: service_healthy # תנאי משופר: האפליקציה תמתין עד שמסד הנתונים ידווח שהוא "בריא" ומוכן לקבל חיבורים

  # הגדרת שירות מסד הנתונים של MySQL
  db:
    # שימוש באימג' הרשמי של MySQL בגרסה 8.0
    image: mysql:8.0
    # הפעלה מחדש אוטומטית במקרה של נפילה
    restart: unless-stopped
    # הגדרת משתני סביבה הנדרשים לאתחול הראשוני של קונטיינר MySQL
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # סיסמה למשתמש ה-root של MySQL
      MYSQL_DATABASE: app               # יוצר אוטומטית מסד נתונים בשם 'app' בעת האתחול הראשון
      MYSQL_USER: retro_user            # יוצר אוטומטית משתמש בשם 'retro_user'
      MYSQL_PASSWORD: 1234              # מגדיר את הסיסמה עבור 'retro_user'
    # מיפוי פורט ה-MySQL מהמחשב המארח לקונטיינר
    ports:
      - "3306:3306"
    # הגדרת volume לאתחול מסד הנתונים. זה החלק החשוב לאיפוס המידע.
    volumes:
      # Docker יריץ אוטומטית כל קובץ .sql שיימצא בתיקייה /docker-entrypoint-initdb.d
      # הפקודה הזו ממפה את התיקייה המקומית 'mysql-init' לתוך הקונטיינר.
      # חשוב: הסקריפטים בתיקייה זו ירוצו רק בפעם הראשונה שהקונטיינר נוצר עם תיקיית נתונים ריקה.
      - ./mysql-init:/docker-entrypoint-initdb.d
    # בדיקת בריאות (healthcheck) שמוודאת שמסד הנתונים באמת מוכן לקבל חיבורים
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s # בדוק כל 10 שניות
      timeout: 5s   # המתן 5 שניות לתשובה
      retries: 5    # נסה 5 פעמים לפני סימון כ"לא בריא"

